package com.careconnect.api;
import com.careconnect.security.JwtService; import com.careconnect.user.*; import jakarta.validation.constraints.*; import java.time.LocalDate; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/auth") @CrossOrigin(origins="http://localhost:5174") public class AuthController {
  private final UserRepository users; private final PasswordEncoder encoder; private final JwtService jwt;
  public AuthController(UserRepository users,PasswordEncoder encoder,JwtService jwt){this.users=users;this.encoder=encoder;this.jwt=jwt;}
  record Register(@NotBlank String firstName,@NotBlank String lastName,@Email String email,@Size(min=8) String password,LocalDate dateOfBirth){} record Login(@Email String email,@NotBlank String password){} record Session(String token,String firstName,String email,String role){}
  @PostMapping("/register") ResponseEntity<?> register(@RequestBody Register input){if(users.findByEmail(input.email()).isPresent())return ResponseEntity.status(409).body("An account already exists for this email.");User u=users.save(new User(input.firstName(),input.lastName(),input.email().toLowerCase(),encoder.encode(input.password()),input.dateOfBirth()));return ResponseEntity.status(HttpStatus.CREATED).body(new Session(jwt.create(u.getEmail()),u.getFirstName(),u.getEmail(),u.getRole()));}
  @PostMapping("/login") ResponseEntity<?> login(@RequestBody Login input){return users.findByEmail(input.email().toLowerCase()).filter(u->encoder.matches(input.password(),u.getPassword())).<ResponseEntity<?>>map(u->ResponseEntity.ok(new Session(jwt.create(u.getEmail()),u.getFirstName(),u.getEmail(),u.getRole()))).orElseGet(()->ResponseEntity.status(401).body("Invalid email or password."));}
}
